import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { AGENDA_COLOURS, parseAgendaColour, agendaAccentClass } from "@/lib/agenda-colours";

describe("parseAgendaColour", () => {
  it("keeps a colour from the palette", () => {
    expect(parseAgendaColour("blue")).toBe("blue");
  });

  it("reads anything else as no colour", () => {
    // The column is free text in the database, so a hand-edited or stale value must fall
    // back to plain rather than emit a class name that does not exist.
    expect(parseAgendaColour("")).toBeNull();
    expect(parseAgendaColour(null)).toBeNull();
    expect(parseAgendaColour("chartreuse")).toBeNull();
    expect(parseAgendaColour("chart-1")).toBeNull();
  });
});

describe("the palette", () => {
  it("offers exactly the inks the token layer has already contrast-checked", () => {
    // Every entry must map to a --chart-N token. Those five are the only colours in this
    // app that have been checked against --card; inventing a sixth would put an unreadable
    // session on an organiser's screen and bypass tests/contrast.test.ts entirely.
    expect(AGENDA_COLOURS.map((c) => c.className)).toEqual(["bg-chart-1", "bg-chart-2", "bg-chart-3", "bg-chart-4", "bg-chart-5"]);
  });

  it("gives every colour a name a person could say out loud", () => {
    for (const c of AGENDA_COLOURS) expect(c.label).toMatch(/^[A-Z][a-z]+$/);
  });
});

describe("class helpers", () => {
  it("gives the colour its accent class", () => {
    expect(agendaAccentClass("blue")).toBe("bg-chart-2");
  });

  it("writes every class out in full, so Tailwind can find it by scanning", () => {
    // A class built from a fragment at runtime is never generated by Tailwind v4 and the
    // colour silently does not render. This test fails if anyone reintroduces one.
    const source = readFileSync("src/lib/agenda-colours.ts", "utf8");
    for (const c of AGENDA_COLOURS) expect(source).toContain(`"${c.className}"`);
  });

  it("returns null for no colour, so an uncoloured session renders exactly as before", () => {
    expect(agendaAccentClass(null)).toBeNull();
    expect(agendaAccentClass("nonsense")).toBeNull();
  });
});
