-- The purge, as one statement instead of two hundred (D172).
--
-- It used to be a loop in TypeScript: select the ids, then one UPDATE per attendee. supabase-js
-- has no transaction (the same constraint book_session works around, D125), so a failure at row
-- 90 of 200 left an event half purged — ninety people anonymised, a hundred and ten not — and
-- threw, so the organiser got an error page and no way to tell which. Re-running would have
-- finished the job, but nothing said so. For an irreversible button behind a confirm dialog,
-- "it half worked" is the one outcome that must not be possible.
--
-- Tokens are generated by the CALLER and passed in, rather than minted here. `attendees.token`
-- is unique and its alphabet lives in src/lib/tokens.ts; a second generator in plpgsql would be
-- a copy of a rule that must never disagree with itself, and it would not learn about a change
-- to the original. TypeScript keeps the alphabet, the database keeps the atomicity.
--
-- `seat_no` is cleared; `category` deliberately is not (D173). Where somebody sat is about that
-- person and is useless once the event is over. Their category is the group their attendance is
-- counted under, and the purge card promises those counts survive.
create or replace function purge_event_personal_data(p_event_id uuid, p_tokens text[])
returns int
language plpgsql
as $$
declare
  purged int;
  needed int;
begin
  select count(*) into needed from attendees where event_id = p_event_id;
  -- Refuse up front rather than run out partway: a NULL token would violate NOT NULL and roll
  -- the whole thing back anyway, but with an error about a constraint instead of about a
  -- caller that did not send enough tokens.
  if needed > coalesce(array_length(p_tokens, 1), 0) then
    raise exception 'purge needs % tokens for event %, got %',
      needed, p_event_id, coalesce(array_length(p_tokens, 1), 0);
  end if;

  with numbered as (
    select id, row_number() over (order by id) as rn
      from attendees
     where event_id = p_event_id
  )
  update attendees a
     set name       = 'Purged',
         email      = null,
         extra      = '{}'::jsonb,
         seat_no    = null,
         token      = p_tokens[numbered.rn],
         status     = 'purged',
         updated_at = now()
    from numbered
   where a.id = numbered.id;

  get diagnostics purged = row_count;
  return purged;
end;
$$;
